### ISSUE TITLE
Issue with background color and some spacing

### ISSUE THREAD

**Issue by theamanjs** [divyanshugarg36/brl-cad-web#28]
I have attached a gif with some mouse movement where the background is ending abruptly. I think the background should be ending after specific height and blocks. Can you please check and fix this? @divyanshugarg36 

![Peek 2022-07-20 16-03](https://user-images.githubusercontent.com/38748298/179961632-1133b082-77d7-4640-a0a9-7b1d85ab1781.gif)

**Comment by divyanshugarg36** [comment]
@theamanjs looks like this is due to the dark mode set up in your device because right now we don't have dark mode in our project and this gif is in dark mode
